// Slugs reserved for the platform — app routes, subdomains, and common terms
// we may want for ourselves — that projects aren't allowed to claim.
export const RESERVED_SLUGS = new Set([
  "account",
  "accounts",
  "admin",
  "api",
  "app",
  "apps",
  "assets",
  "auth",
  "billing",
  "blog",
  "cdn",
  "contact",
  "create",
  "dashboard",
  "docs",
  "ferri",
  "files",
  "folders",
  "help",
  "internal",
  "links",
  "login",
  "logout",
  "mail",
  "me",
  "new",
  "pricing",
  "privacy",
  "project",
  "projects",
  "public",
  "settings",
  "signin",
  "sign-in",
  "signup",
  "sign-up",
  "static",
  "status",
  "support",
  "system",
  "terms",
  "test",
  "tests",
  "testing",
  "user",
  "users",
  "www",
]);

export function isReservedSlug(slug: string): boolean {
  return RESERVED_SLUGS.has(slug.toLowerCase());
}
